
version: "3.8"
services:
  nginx:
    container_name: ${NAME}_nginx
    hostname: ${NAME}_nginx
    restart: always
    ports:
      - ${HTTP_PORT}:80
    build:
      context: ${DOCKER_PATH}/nginx
      dockerfile: Dockerfile
    volumes:
      - ./${DOCKER_PATH}/${HTTP_LOCAL_CONFIG_PATH}:${HTTP_CONTAINER_CONFIG_PATH}:ro
      - ./${APP_LOCAL_PATH}:${APP_CONTAINER_PATH}

  postgres:
    container_name: ${NAME}_postgres
    hostname: ${NAME}_postgres
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    build:
      context: ${DOCKER_PATH}/postgres
      dockerfile: Dockerfile
    environment:
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_ROOT_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - .:/docker-entrypoint-initdb.d
      - dbdata:${POSTGRES_DBDATA}

  php-fpm:
    container_name: ${NAME}_php-fpm
    hostname: ${NAME}_php-fpm
    environment:
      docker: "true"
    extra_hosts:
      - ${PHP_FPM_EXTRA_HOST}
    build:
      context: ${DOCKER_PATH}/php-fpm
      dockerfile: Dockerfile
      args:
        - INSTALL_FAKETIME=false
        - INSTALL_LOCALES_ADDITIONAL=false
        - LOCALES_ADDITIONAL=${LOCALES_ADDITIONAL}
        - LOCALE=${LOCALE_DEFAULT}
        - TIMEZONE=${TIMEZONE_DEFAULT}
        - http_proxy
        - https_proxy
        - no_proxy
        - PUID=${PUID}
        - PGID=${PGID}
    env_file:
      - ${DOCKER_PATH}/php-fpm/xdebug.env
    volumes:
      - ./${APP_LOCAL_PATH}:${APP_CONTAINER_PATH}
      - ./${DOCKER_PATH}/php-fpm/php.ini:${PHP_FPM_CONFIG_PATH}:ro
    depends_on:
      - nginx
      - postgres

  node:
    container_name: ${NAME}_node
    hostname: ${NAME}_node
    environment:
      docker: "true"
    build:
      context: ${DOCKER_PATH}/node
      dockerfile: Dockerfile
    volumes:
      - ./${APP_LOCAL_PATH}:${APP_CONTAINER_PATH}
    depends_on:
      - php-fpm
  
  composer:
    container_name: ${NAME}_composer
    hostname: ${NAME}_composer
    environment:
      docker: "true"
    build:
      context: ${DOCKER_PATH}/composer
      dockerfile: Dockerfile
    volumes:
      - ./${APP_LOCAL_PATH}:${APP_CONTAINER_PATH}
    depends_on:
      - php-fpm

  memcached:
    container_name: ${NAME}_memcached
    hostname: ${NAME}_memcached
    restart: always
    ports:
      - ${MEMCACHED_PORT}:5000
    build:
      context: ${DOCKER_PATH}/memcached
      dockerfile: Dockerfile
    volumes:
      - cachedata:${MEMCACHED_CACHEDATA}
    depends_on:
      - nginx
      - postgres
      - php-fpm


volumes:
  dbdata:
    driver: local
  cachedata:
    driver: local
        